### ISSUE TITLE
Since 1.06 some ino do not compile

### ISSUE THREAD

**Issue by fpistm** [arduino-libraries/LiquidCrystal#16]
It seems it misses a carriage return in the comment:
`// with the arduino pin number it is connected toconst int rs=12, en=11, d4=5, d5=4, d6=3, d7=2;`
should be:
`// with the arduino pin number it is connected to`
`const int rs=12, en=11, d4=5, d5=4, d6=3, d7=2;`

Impacted sketch:

- Blink.ino
- Cursor.ino

**Comment by facchinm** [comment]
Fixed by https://github.com/arduino-libraries/LiquidCrystal/commit/9af7b43bdd92833521ec6d521990a84683857e70, thnaks for reporting!
