### ISSUE TITLE
"lcd.print"

### ISSUE THREAD

**Issue by Nadlod** [arduino-libraries/LiquidCrystal#36]
Im begin a project for my school where I need create a personal library like LiquidCrystal, the work is awesome and legible but I dont can found where is defined lcd.print.Please help me.

The example is "Hello World" I see the lcd.print but in LiquidCrystal.h and .cpp i dont found nothing except:

 " virtual size_t write(uint8_t);

    using Print::write;    "

"inline size_t LiquidCrystal::write(uint8_t value) {
  send(value, HIGH);
  return 1; // assume sucess "

"void LiquidCrystal::write4bits(uint8_t value) {
  for (int i = 0; i < 4; i++) {
    digitalWrite(_data_pins[i], (value >> i) & 0x01);"

**Comment by per1234** [comment]
Hi @Nadlod. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This type of question is more appropriate for the Arduino Forum. If by chance you never found the answer and are still interested, I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
