### ISSUE TITLE
print wrong charcters

### ISSUE THREAD

**Issue by reshma26994** [arduino-libraries/LiquidCrystal#55]
hello,
i interfaced lcd 16x2 by 4 bit mode with esp32 and GPIO connect as rs-io17,en-io16,d4-io18,d5-io19,d6-io1,d7-io23
LiquidCrystal lcd(17, 16, 18, 19, 1, 23);
and try for print hello world but it prints "l" instead of"h" and also problem in other characters
please give me replay as soon as possible!!

**Comment by reshma26994** [comment]
please give me replay as soon as possible

**Comment by per1234** [comment]
Hi @reshma26994. Thanks for your interest in this open source project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
