### ISSUE TITLE
How can add delay instead of delay function

### ISSUE THREAD

**Issue by Eldho1416** [arduino-libraries/LiquidCrystal#63]
Hi, 

I'm calling a function to print a dynamic string in LCD and i have been using delay which is stopping my program from other process, I also used millis but didn't help 

what can i do here?

**Comment by per1234** [comment]
Hi @Eldho1416. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
