### ISSUE TITLE
LiquidCrystal causing ESP32-S2-Wrover-I to crash.

### ISSUE THREAD

**Issue by 9500753429** [arduino-libraries/LiquidCrystal#81]

**Comment by per1234** [comment]
Hi @9500753429. Thanks for your interest in this open source project. This issue tracker is only to be used to submit high quality formal bug reports or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
